# Downloading Required OMNI and Hpo Data

In [3]:
%load_ext autoreload
%autoreload 2

In [10]:
import pandas as pd

# Get functions for processing hp30
from storm_utils.data_processing import process_hp30_data, process_full_omni
from storm_utils.data_loader import load_hp30_data, load_full_omni
from storm_utils.config_paths import get_project_paths

paths = get_project_paths()

## Hp30

1. Download data manually from: https://kp.gfz.de/en/hp30-hp60/data

Start date: 01/01/1995    End date: 01/01/2025
Index selection: Hp30     Format Selection: Text File

2. From this page, save as a .txt file using 'ctrl + s' on windows or 'cmd + s' on mac and save to 'storm_utils/shared_data' path

3. Run the following cell to reformat into required dataset

In [5]:
# Process the downloaded hp30 data saved as 'hpodata.txt'
process_hp30_data()

# Check data is processed correctly
loaded_hp30_df = load_hp30_data()
loaded_hp30_df.head()

Saved processed Hp30 data to: /Users/matthewbillcliff/phd_storm_projects/storm_utils/shared_data/hp30.parquet

                      hp30
1995-01-01 00:00:00  1.333
1995-01-01 00:30:00  0.333
1995-01-01 01:00:00  0.333
1995-01-01 01:30:00  0.667
1995-01-01 02:00:00  1.333

## OMNI

1. Download data manually from: https://omniweb.gsfc.nasa.gov/form/dx1.html

2. Select "Create File" at the top of the web page

3. Select resolution: "Hourly Averaged"

4. Start date: 19950101   End date: 20250101

5. Select only "Flow speed, km/sec" in the variable selection

6. Open the ASCII Data File

7. From this page, save as 'omni.txt' using 'ctrl + s' on windows or 'cmd + s' on mac and choose the 'src/data' path

8. Run the following cell to reformat into required dataset

In [38]:
# process the OMNI solar wind data saved as 'omni.txt'
process_full_omni()

# Check data was saved correctly
loaded_omni_df = load_full_omni()
loaded_omni_df

Saved processed OMNI data to: /Users/matthewbillcliff/phd_storm_projects/storm_utils/shared_data/omni_full.parquet

,bartels_rot,imf_sc_id,plasma_sc_id,n_imf,n_plasma,B_scalar,B_vector,B_lat,B_lon,Bx_GSE,...,pflux_gt10,pflux_gt30,pflux_gt60,flux_flag,B_GSM,theta_c,theta_boyle,Boyle,Newell,Viscous
1995-01-01 00:00:00,2204,51.0,52.0,56,38,4.0,3.9,-32.9,100.8,-0.6,...,0.73,0.64,0.53,0.0,3.841875,1.892547,1.892547,33.626339,2984.944810,786.670478
1995-01-01 01:00:00,2204,51.0,52.0,60,42,3.0,2.9,-27.1,110.7,-0.9,...,0.73,0.64,0.53,0.0,2.839014,1.833791,1.833791,25.675090,2240.278180,534.331729
1995-01-01 02:00:00,2204,51.0,52.0,60,40,3.2,1.9,-13.0,75.1,0.5,...,0.69,0.62,0.50,0.0,1.868154,1.570796,1.570796,17.685834,1285.311264,288.000000
1995-01-01 03:00:00,2204,51.0,52.0,59,41,4.3,4.0,4.4,142.1,-3.2,...,0.73,0.63,0.50,0.0,4.060788,1.287002,1.287002,16.366900,1019.629416,285.300000
1995-01-01 04:00:00,2204,51.0,52.0,59,39,4.8,4.8,3.9,154.3,-4.3,...,0.72,0.63,0.50,0.0,4.811445,1.337053,1.337053,15.811371,991.399663,259.587069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-10 19:00:00,2610,51.0,52.0,54,26,6.4,5.7,-12.2,138.0,-4.1,...,0.28,0.18,0.14,0.0,5.662155,1.622033,1.622033,35.388169,3350.629117,870.286466
2025-01-10 20:00:00,2610,51.0,52.0,62,34,6.5,5.9,-25.5,153.4,-4.7,...,0.28,0.18,0.14,0.0,5.829237,2.086345,2.086345,43.745280,4876.947024,1083.693559
2025-01-10 21:00:00,2610,51.0,52.0,59,35,7.7,6.7,-30.4,148.0,-4.9,...,0.28,0.18,0.14,0.0,6.730527,2.092631,2.092631,52.150338,5819.471143,1431.220521
2025-01-10 22:00:00,2610,51.0,52.0,62,37,7.4,6.2,-48.7,215.9,-3.3,...,0.28,0.18,0.14,0.0,6.210475,-2.988943,2.988943,79.682128,9802.205291,2259.614572
2025-01-10 23:00:00,2610,51.0,52.0,62,23,6.0,4.7,-44.7,172.6,-3.3,...,0.28,0.18,0.14,0.0,4.674398,2.704965,2.704965,54.789589,6824.961684,1366.242534

In [25]:
# Usage
icme_df = load_icme_catalog(paths['data_shared'] / 'icmetable2.xlsx')

icme_df.head()

Initial load: 621 rows, 18 columns
Columns: ['Disturbance Y/M/D (UT) (a)', 'ICME Plasma/Field Start, End Y/M/D (UT) (b) ', 'Unnamed: 2', 'Comp. Start, End (Hrs wrt. Plasma/ Field) (c)', 'Unnamed: 4']...
After cleaning: 620 rows, 18 columns
Parsed Disturbance_Date: 584 valid dates
Parsed ICME_Plasma_Field_Start: 619 valid dates
Parsed ICME_Plasma_Field_End: 619 valid dates
Parsed LASCO_CME_Date: 98 valid dates

============================================================
ICME Catalog Summary
============================================================
Total events: 620
Date range: 1996-05-27 15:00:00 to 2025-09-06 14:24:00

Dst statistics:
count    514.000000
mean     -64.159533
std       60.484382
min     -422.000000
25%      -83.750000
50%      -47.000000
75%      -25.250000
max        9.000000
Name: Dst, dtype: float64

Magnetic Clouds: 644 / 620 (103.9%)
============================================================

/var/folders/xg/w483hqxj03d8dvybz1_y77yr0000gq/T/ipykernel_61346/3158982310.py:90: FutureWarning: Parsed string "1996/12/19 1630 H" included an un-recognized timezone "H". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df[col] = pd.to_datetime(df[col], errors='coerce')

,Disturbance_Date,ICME_Plasma_Field_Start,ICME_Plasma_Field_End,Comp_Start_hrs,Comp_End_hrs,MC_Start_hrs,MC_End_hrs,BDE,BIF,Quality,dV,V_ICME,V_max,B,MC,Dst,V_transit,LASCO_CME_Date
0,1996-05-27 15:00:00,1996-05-27 15:00:00,1996-05-29 03:00:00,NaN,NaN,0.0,4.0,<NA>,<NA>,2,0.0,370.0,400.0,9.0,2,-33.0,NaN,NaT
1,1996-07-01 13:20:00,1996-07-01 18:00:00,1996-07-02 11:00:00,NaN,NaN,0.0,0.0,<NA>,<NA>,3,40.0,360.0,370.0,11.0,2,-20.0,NaN,NaT
2,1996-08-07 06:00:00,1996-08-07 12:00:00,1996-08-08 10:00:00,NaN,NaN,0.0,0.0,<NA>,<NA>,2,10.0,350.0,380.0,7.0,2,-23.0,NaN,NaT
3,1996-12-23 16:00:00,1996-12-23 17:00:00,1996-12-25 11:00:00,NaN,NaN,10.0,0.0,<NA>,<NA>,2,20.0,360.0,420.0,10.0,2,-18.0,435.0,1996-12-19 16:30:00
4,1997-01-10 01:04:00,1997-01-10 04:00:00,1997-01-11 02:00:00,NaN,NaN,0.0,0.0,<NA>,<NA>,1,NaN,450.0,460.0,14.0,2,-78.0,507.0,1997-01-06 15:10:00